### ISSUE TITLE
Feature for scanning OCI Image given tag

### ISSUE THREAD

**Issue by shimish2** [aquasecurity/fanal#120]
I am looking for a feature for scanning an OCI image given an image name and tag. 

I have done the necessary changes, please let me know if I can send an PR for the same and provide further details.

**Comment by knqyf263** [comment]
It would be helpful if you send us the PR!

**Comment by shimish2** [comment]
[https://github.com/aquasecurity/fanal/pull/130](url)

**Comment by shimish2** [comment]
#130
