### ISSUE TITLE
Support local cache of APK index

### ISSUE THREAD

**Issue by patrick-stephens** [aquasecurity/fanal#124]
An extension of https://github.com/aquasecurity/fanal/issues/63 but to provide access to the APK cache from a local file:/// URL. It appears the Go http.get call does not like the "file" protocol.

To support running completely offline in an embedded environment where additional web servers may not be allowed/possible. At the moment, we take an offline copy of the database and the APK index to use all within the container. Unfortunately it requires running a local web server to serve the APK index which is quite bulky.

It may be I have missed something to allow local file-based URLs to provide the APK index: my Go knowledge is sadly lacking. Happy to also look at a pull request to resolve it.

**Comment by knqyf263** [comment]
@rahul2393 Please find the detail in this issue. Also, we should provide the option to skip the APK index.

**Comment by simar7** [comment]
@patrick-stephens looks like https://github.com/aquasecurity/fanal/pull/133 is merged now. Have you tried this?

**Comment by patrick-stephens** [comment]
Not yet as we're not set up to build from source currently: I can't see that it is in a release yet. I was going to test it as part of the next release and offline updates for that.

The changes look good so happy to close based on that.
