### ISSUE TITLE
Downloading content from knqyf263 ? 

### ISSUE THREAD

**Issue by adamdecaf** [aquasecurity/fanal#216]
Hey there! This project looks cool, but I was wondering why it downloads from an arbitrary Github user? If that account is compromised the impact could be silent failures, crashes, etc 

https://github.com/aquasecurity/fanal/blob/main/analyzer/command/apk/apk.go#L27

**Comment by knqyf263** [comment]
I'm a creator of fanal and [trivy](https://github.com/aquasecurity/trivy) and joined Aqua Security with these projects. Some repositories are not transferred to Aqua Security yet.

**Comment by adamdecaf** [comment]
Congrats! Thanks for letting me know.
