### ISSUE TITLE
disable secret scanning?

### ISSUE THREAD

**Issue by zetaab** [aquasecurity/fanal#515]
It seems https://github.com/aquasecurity/fanal/blob/main/artifact/local/fs.go#L55 that secret scanning is always enabled and not possible to disable it? We are seeing that this is using quite much resources and would like to disable it. Is that possible?

with secret scanning our scan takes something like 10 minutes and eat all ram/cpu from the machine. Without secret scanner it takes 2-4 seconds.

**Comment by knqyf263** [comment]
Please refer to this page.
https://aquasecurity.github.io/trivy/v0.27.1/docs/secret/scanning/
