### ISSUE TITLE
Improve fanal caching

### ISSUE THREAD

**Issue by simar7** [aquasecurity/fanal#52]
Currently fanal caches accumulate endlessly as described in this issue: https://github.com/aquasecurity/trivy/issues/260

This can also be seen here: https://github.com/aquasecurity/trivy/issues/101

This issue has been created to track the improvement of fanal caching. 

The following PRs are associated with addressing this issue:
* Improve testing and refactor: https://github.com/aquasecurity/fanal/pull/47
* Using a KV store for caching: https://github.com/aquasecurity/fanal/pull/49
* Improving KV store performance to store only required files: https://github.com/aquasecurity/fanal/pull/51

**Comment by dvianello** [comment]
Hey - any movement on this? 

Recently added trivy to our Harbor deployment on K8S and quickly got into troubles with cache growing considerably while doing a sweep scan of a replicated repository. In the end we had to exec into containers and manually delete the fanal cache, but that's not exactly a nice way of solving it!

Thanks,
Dario

**Comment by knqyf263** [comment]
Yes, this was fixed by this PR https://github.com/aquasecurity/fanal/pull/84. I forgot to close this issue.

You can try it through harbor-scanner-trivy v0.3.0.
https://github.com/aquasecurity/harbor-scanner-trivy/releases/tag/v0.3.0
