### ISSUE TITLE
Add benchmarks in Docker mode

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/fanal#69]

**Comment by simar7** [comment]
Could you add some acceptance criteria for this issue to be considered done? Here's what I can think of top of my head:

Acceptance criteria:
* As a user of Fanal library, I would like to see gradual performance improvements with newer commits.
* If a newer commit is worse in performance* than the ones before, it will not be merged until it is improved to be better.
* If a newer commit is better in performance than the ones before, it will be OK to be picked into master.


[*]: Worse in performance: Should we quantify this number? 5% worse? 10% worse? something else?

Thoughts?

**Comment by simar7** [comment]
For now I have added something here https://github.com/aquasecurity/fanal/pull/71
